[tool.poetry]
name = "aoc-solution-cli"
version = "0.1.0"
description = ""
authors = ["taitep <arvid@h.se>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
